Write-Host "= (01)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_7zr.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (02)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_7zip.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (03)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_notepad++.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (04)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_vscode.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (05)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_git.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (06)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_powershell7.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (07)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_net8sdk.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (08)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_conan.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (09)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_sarasa.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= (10)/10 進度 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_vcbuildtools.ps1" -UseBasicParsing).Content | Invoke-Expression