Write-Host "= 進度 1/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_7zr.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 2/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_7zip.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 3/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_notepad++.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 4/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_vscode.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 5/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_git.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 6/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_powershell7.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 7/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_net8sdk.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 8/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_conan.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 9/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_sarasa.ps1" -UseBasicParsing).Content | Invoke-Expression
Write-Host "= 進度 10/10 ="
(Invoke-WebRequest "https://raw.githubusercontent.com/kiloath/Installer/main/install_vcbuildtools.ps1" -UseBasicParsing).Content | Invoke-Expression