FROM rust
WORKDIR /kiloath
COPY *.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
RUN curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash
RUN mv ./spin /usr/local/bin/spin
RUN rustup target add wasm32-wasi

ENTRYPOINT ["spin"]
CMD [ "--version" ]

# docker build -t kospin -f Dockerfile_spin .
